language: r
# Using the package cache to store R package dependencies can significantly speed up build times and is recommended for most builds.
cache: packages

# run on a few r versions
r:
  - oldrel
  - release
  - devel
 
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change
  slack: 
    hrug:cCFFPSuKEkld9WUDvRmaoRAt

# https://docs.travis-ci.com/user/languages/r/
