# https://docs.travis-ci.com/user/languages/r/


language: r
cache: packages

# run on a few r versions
r:
  - oldrel
  - release
  - devel
 
 repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change
  slack: 
    hrug:cCFFPSuKEkld9WUDvRmaoRAt
